START = 'start'
STOP = 'stop'
FINISH = 'finish'
PAY = 'pay'
GET = 'get'
LIFE = 'life'
PAYDAY = 'payday'
SPECIAL = 'special'

BANK = 'bank'

DOCTOR = 'doctor'
ACCOUNTANT = 'accountant'
ARTIST = 'artist'
ENTERTAINER = 'entertainer'
SALES = 'salesperson'
COP = 'police officer'
TEACHER = 'teacher'
ATHLETE = 'athlete'
TECH = 'computer consultant'

PAYRED = 'red'
PAYGREEN = 'green'
PAYPURPLE = 'purple'
PAYYELLOW = 'yellow'